### ISSUE TITLE
Use References in Requests Where Possible

### ISSUE THREAD

**Issue by Nerixyz** [twitch-rs/twitch_api#261] opened 2022-07-31 15:08 UTC
Currently, most request structs use owned types for the request. However, they only need to serialize the request, thus they only need immutable references to the data.

Take the `GetUsersRequest` as an example:

https://github.com/twitch-rs/twitch_api/blob/607b9aed06b4168db548997d445f739fbb297a26/src/helix/endpoints/users/get_users.rs#L48-L55

The `id` and `login` should really be `&[&types::User{Id,Name}Ref]`.

**Comment by Emilgardis** [comment] 2022-07-31 17:09
This is a duplicate of #114

This is definitely something I want solved, the hard part is how to do it and allow owning the data. (Cow comes to mind, which we've managed to implement fairly well in [`twitch-irc`](https://crates.io/crates/twitchchat), but not to a level I feel works well.

**Closed** 2022-07-31 17:09 UTC

**Comment by Nerixyz** [comment] 2022-07-31 17:21
Sorry, I didn't see the issue.
